In [1]:
# Dependencies
import requests
import json
import pandas as pd
import pymongo

In [2]:
# The default port used by MongoDB is 27017
# https://docs.mongodb.com/manual/reference/default-mongodb-port/
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)
db = client.marketdata

In [3]:
# Portfolio list and get the string list
# read from UI and insert into mongoDB 
symbol_dict = [{'symbol':'AAPL','active':'Y'},
               {'symbol':'TSLA','active':'Y'},
               {'symbol':'VOO','active':'Y'},
               {'symbol':'BABA','active':'Y'},
               {'symbol':'JPM','active':'Y'}]

In [4]:
# Insert a document into the 'portfolio' collection
# Read existing data from MongoDB
portfolio = db.portfolio.find()
is_data_found=db.portfolio.count()


data = pd.DataFrame(list(portfolio))
data
print(is_data_found)

# from new list above
for i in range(len(symbol_dict)):
    #print(list_index[i]['symbol'])
    cnt=0
    # avoid duplicate check if symbol is already active in DB
    if is_data_found !=0:
        cnt=data[(data['active']==symbol_dict[i]['active']) & (data['symbol']==symbol_dict[i]['symbol'])]['symbol'].count()
    else:
        # first record
        cnt=1
        
    if (cnt!=0 | is_data_found==0):
        db.portfolio.insert_one(symbol_dict[i])

5

/Users/Shiva/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere
  after removing the cwd from sys.path.

In [4]:
symbol_df = pd.DataFrame.from_dict(db.portfolio.find())
#symbol_df=symbol_df.append({'symbol':'TSLA','active':'Y'},ignore_index=TRUE)
active_symbol= list(symbol_df[symbol_df['active']=='Y']['symbol'])  
symbol_str=''
for i in range(len(active_symbol)):
    if i == len(active_symbol)-1:
        symbol_str = symbol_str + active_symbol[i] 
    else:
        symbol_str = symbol_str + active_symbol[i] + '%2C'

symbol_str

'AAPL%2CTSLA%2CVOO%2CBABA%2CJPM'

In [5]:
# URL for GET requests to retrieve symbol data
# append the active symbol from above list
url = "https://marketdata.websol.barchart.com/getQuote.json?apikey=0b6bf035918d6d5e9f4b803bded9a20f&fields=fiftyTwoWkHigh%2CfiftyTwoWkHighDate%2CfiftyTwoWkLow%2CfiftyTwoWkLowDate%2Ctick&symbols="+symbol_str

In [6]:
# Pretty print JSON for all launchpads
response = requests.get(url)
response_json = response.json()

In [7]:
# rearrange dataset
#df[['symbol','close']]
#new_df = df[['symbol','name','open','lastPrice','netChange','tradeTimestamp',
#             'fiftyTwoWkHigh','fiftyTwoWkHighDate','fiftyTwoWkLow','fiftyTwoWkLowDate','serverTimestamp']]
#new_df

In [27]:
# using db = client.marketdata

# Query all marketdata
# Here, get the daily index price to dataframe
index_price = db.index_price.find()
is_data_found=db.index_price.count()

#list_index=response_json["results"] 
if is_data_found !=0:
    data = pd.DataFrame(list(index_price))
    data
print(is_data_found)
data

10

/Users/Shiva/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere

,_id,close,dayCode,exchange,fiftyTwoWkHigh,fiftyTwoWkHighDate,fiftyTwoWkLow,fiftyTwoWkLowDate,flag,high,...,name,netChange,open,percentChange,serverTimestamp,symbol,tick,tradeTimestamp,unitCode,volume
0,5da343f1b4883299713008bd,236.21,0,BATS,237.64,2019-10-11,142.00,2019-01-03,s,0.00,...,Apple Inc,236.21,0.00,0.00,2019-10-13T02:35:08-05:00,AAPL,,2019-10-10T00:00:00-05:00,2,0
1,5da343f1b4883299713008be,247.89,0,BATS,379.49,2018-12-07,176.99,2019-06-03,s,0.00,...,Tesla Inc,247.89,0.00,0.00,2019-10-13T03:15:58-05:00,TSLA,,2019-10-10T00:00:00-05:00,2,0
2,5da343f1b4883299713008bf,272.13,0,BATS,277.98,2019-09-19,214.83,2018-12-26,s,0.00,...,S&P 500 ETF Vanguard,272.13,0.00,0.00,2019-10-13T09:45:02-05:00,VOO,,2019-10-10T00:00:00-05:00,2,0
3,5da343f1b4883299713008c0,172.94,0,BATS,195.72,2019-05-03,129.77,2018-12-24,s,0.00,...,Alibaba Group Holding,172.94,0.00,0.00,2019-10-13T08:46:04-05:00,BABA,,2019-10-10T00:00:00-05:00,2,0
4,5da343f1b4883299713008c1,116.14,0,BATS,120.40,2019-09-13,91.11,2018-12-26,s,0.00,...,JP Morgan Chase & Company,116.14,0.00,0.00,2019-10-13T04:18:42-05:00,JPM,,2019-10-10T00:00:00-05:00,2,0
5,5da51abd84fd000e0dc62d9c,235.87,D,NASDAQ,238.13,2019-10-14,142.00,2019-01-03,s,238.13,...,Apple Inc,-0.34,234.90,-0.14,2019-10-14T00:00:00-05:00,AAPL,,2019-10-14T00:00:00-05:00,2,24392500
6,5da51abd84fd000e0dc62d9d,256.96,D,NASDAQ,379.49,2018-12-07,176.99,2019-06-03,s,258.55,...,Tesla Inc,9.07,247.90,3.66,2019-10-14T00:00:00-05:00,TSLA,,2019-10-14T00:00:00-05:00,2,10223300
7,5da51abd84fd000e0dc62d9e,271.88,D,AMEX,277.98,2019-09-19,214.83,2018-12-26,s,272.45,...,S&P 500 ETF Vanguard,-0.25,271.79,-0.09,2019-10-14T00:00:00-05:00,VOO,,2019-10-14T00:00:00-05:00,2,1216400
8,5da51abd84fd000e0dc62d9f,171.16,D,NYSE,195.72,2019-05-03,129.77,2018-12-24,s,173.34,...,Alibaba Group Holding,-1.78,172.84,-1.03,2019-10-14T00:00:00-05:00,BABA,,2019-10-14T00:00:00-05:00,2,7854100
9,5da51abd84fd000e0dc62da0,116.45,D,NYSE,120.40,2019-09-13,91.11,2018-12-26,s,116.87,...,JP Morgan Chase & Company,0.31,115.85,0.27,2019-10-14T00:00:00-05:00,JPM,,2019-10-14T00:00:00-05:00,2,8872000

[[ObjectId('5da343f1b4883299713008bd'),
  236.21,
  '0',
  'BATS',
  237.64,
  '2019-10-11',
  142.0,
  '2019-01-03',
  's',
  0.0,
  236.21,
  0.0,
  'i',
  'Apple Inc',
  236.21,
  0.0,
  0.0,
  '2019-10-13T02:35:08-05:00',
  'AAPL',
  '',
  '2019-10-10T00:00:00-05:00',
  '2',
  0],
 [ObjectId('5da343f1b4883299713008be'),
  247.89,
  '0',
  'BATS',
  379.49,
  '2018-12-07',
  176.99,
  '2019-06-03',
  's',
  0.0,
  247.89,
  0.0,
  'i',
  'Tesla Inc',
  247.89,
  0.0,
  0.0,
  '2019-10-13T03:15:58-05:00',
  'TSLA',
  '',
  '2019-10-10T00:00:00-05:00',
  '2',
  0],
 [ObjectId('5da343f1b4883299713008bf'),
  272.13,
  '0',
  'BATS',
  277.98,
  '2019-09-19',
  214.83,
  '2018-12-26',
  's',
  0.0,
  272.13,
  0.0,
  'i',
  'S&P 500 ETF Vanguard',
  272.13,
  0.0,
  0.0,
  '2019-10-13T09:45:02-05:00',
  'VOO',
  '',
  '2019-10-10T00:00:00-05:00',
  '2',
  0],
 [ObjectId('5da343f1b4883299713008c0'),
  172.94,
  '0',
  'BATS',
  195.72,
  '2019-05-03',
  129.77,
  '2018-12-24',
  's',
  0.0,
  172.94,
  0.0,
  'i',
  'Alibaba Group Holding',
  172.94,
  0.0,
  0.0,
  '2019-10-13T08:46:04-05:00',
  'BABA',
  '',
  '2019-10-10T00:00:00-05:00',
  '2',
  0],
 [ObjectId('5da343f1b4883299713008c1'),
  116.14,
  '0',
  'BATS',
  120.4,
  '2019-09-13',
  91.11,
  '2018-12-26',
  's',
  0.0,
  116.14,
  0.0,
  'i',
  'JP Morgan Chase & Company',
  116.14,
  0.0,
  0.0,
  '2019-10-13T04:18:42-05:00',
  'JPM',
  '',
  '2019-10-10T00:00:00-05:00',
  '2',
  0],
 [ObjectId('5da51abd84fd000e0dc62d9c'),
  235.87,
  'D',
  'NASDAQ',
  238.13,
  '2019-10-14',
  142.0,
  '2019-01-03',
  's',
  238.13,
  235.87,
  234.67,
  'd',
  'Apple Inc',
  -0.34,
  234.9,
  -0.14,
  '2019-10-14T00:00:00-05:00',
  'AAPL',
  '',
  '2019-10-14T00:00:00-05:00',
  '2',
  24392500],
 [ObjectId('5da51abd84fd000e0dc62d9d'),
  256.96,
  'D',
  'NASDAQ',
  379.49,
  '2018-12-07',
  176.99,
  '2019-06-03',
  's',
  258.55,
  256.96,
  247.13,
  'd',
  'Tesla Inc',
  9.07,
  247.9,
  3.66,
  '2019-10-14T00:00:00-05:00',
  'TSLA',
  '',
  '2019-10-14T00:00:00-05:00',
  '2',
  10223300],
 [ObjectId('5da51abd84fd000e0dc62d9e'),
  271.88,
  'D',
  'AMEX',
  277.98,
  '2019-09-19',
  214.83,
  '2018-12-26',
  's',
  272.45,
  271.88,
  271.48,
  'd',
  'S&P 500 ETF Vanguard',
  -0.25,
  271.79,
  -0.09,
  '2019-10-14T00:00:00-05:00',
  'VOO',
  '',
  '2019-10-14T00:00:00-05:00',
  '2',
  1216400],
 [ObjectId('5da51abd84fd000e0dc62d9f'),
  171.16,
  'D',
  'NYSE',
  195.72,
  '2019-05-03',
  129.77,
  '2018-12-24',
  's',
  173.34,
  171.16,
  170.79,
  'd',
  'Alibaba Group Holding',
  -1.78,
  172.84,
  -1.03,
  '2019-10-14T00:00:00-05:00',
  'BABA',
  '',
  '2019-10-14T00:00:00-05:00',
  '2',
  7854100],
 [ObjectId('5da51abd84fd000e0dc62da0'),
  116.45,
  'D',
  'NYSE',
  120.4,
  '2019-09-13',
  91.11,
  '2018-12-26',
  's',
  116.87,
  116.45,
  115.66,
  'd',
  'JP Morgan Chase & Company',
  0.31,
  115.85,
  0.27,
  '2019-10-14T00:00:00-05:00',
  'JPM',
  '',
  '2019-10-14T00:00:00-05:00',
  '2',
  8872000]]

In [68]:
# Iterate through each indexprice in the collection
# insert into DB for index price

# Insert a document into the 'indexprice' collection
list_index=response_json["results"] 
#len(list_index)
for i in range(len(list_index)):
    #print(list_index[i]['symbol'])
    cnt=0
    #print(list_index[i]['serverTimestamp'])
    #print(data['tradeTimestamp']==list_index[i]['tradeTimestamp'])
    # avoid duplicate
    #if is_data_found !=0:
    #    cnt=data[(data['tradeTimestamp']==list_index[i]['tradeTimestamp']) & (data['symbol']==list_index[i]['symbol'])]['symbol'].count()
        # if cnt is zero then its a new record
        #print(cnt)
    #    if (cnt == 0):
    #       cnt=1 
    #else:
        # first record
    #    cnt=1
        
    #if record exists ignore the exception
    if (cnt!=0) | (is_data_found==0):
        try:
            db.index_price.insert_one(list_index[i])
        except Exception:
            pass
    
print("Total number of records in index_list in database is:", db.index_price.count())

Total number of records in index_list in database is: 10

/Users/Shiva/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:30: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere

In [16]:
# Iterate through each symbol in the collection, uncomment the code to see the results
#index_price = db.index_price.find()
#for ind in index_price:
#len(list_index)
#print(is_data_found)
#list_index[0]['serverTimestamp']
#    print(ind)
#for i in range(len(index_price)):
#    print(index_price[i])

In [75]:
# TO populate the history record read through individual symbol and gather the data in list
symbol_df = pd.DataFrame.from_dict(db.portfolio.find()) 
active_symbol=[]
active_symbol= list(symbol_df[symbol_df['active']=='Y']['symbol'])  
#symbol_str=''

hist_list_index=[]
hist_index=[]

hist_url= "https://marketdata.websol.barchart.com/getHistory.json?apikey=0b6bf035918d6d5e9f4b803bded9a20f&type=minutes&startDate=20190801&endDate=20191011&maxRecords=100&interval=60&order=asc&sessionFilter=EFK&splits=true&dividends=true&volume=sum&nearby=1&jerq=true&exchange=NYSE%2CAMEX%2CNASDAQ&backAdjust=false&daysToExpiration=1&contractRoll=expiration&symbol="

for i in range(len(active_symbol)):
    hist_response = requests.get(hist_url+active_symbol[i])
    #print(hist_url+active_symbol[i])
    hist_response_json = hist_response.json()
    hist_index = hist_response_json["results"]
    for i in range(len(hist_index)):
        hist_list_index.append(hist_index[i])



#len(hist_list_index)
#len(hist_list_index[0])

#for i in range(len(hist_list_index)):
#    print(hist_list_index[i])

In [76]:
# Iterate through each history indexprice in the collection
# insert into DB for history ndex price

# Insert a document into the 'indexprice' collection
# Query all marketdata
# Here, get the daily index price to dataframe
index_price = db.index_price_hist.find()
is_data_found=db.index_price_hist.count()

 
data = pd.DataFrame(list(index_price))
data
print(is_data_found)

# use hist_list_index from above
for i in range(len(hist_list_index)):
    #print(list_index[i])
    #db.index_price_hist.insert_one(hist_list_index[i])
        #print(list_index[i]['symbol'])
    #cnt=0
    # avoid duplicate
    # check if the symbol and systemTimestamp record is found
    #if is_data_found !=0:
    #    cnt=data[(data['timestamp']==hist_list_index[i]['timestamp']) & (data['symbol']==hist_list_index[i]['symbol'])]['symbol'].count()
    # else:
        # first record
        # cnt=1
        
    #if record exists ignore the exception
    
    try:
        db.index_price_hist.insert_one(hist_list_index[i])
    except Exception:
        pass
        
    #if (cnt!=0 | is_data_found==0):
        #db.index_price_hist.insert_one(hist_list_index[i])

/Users/Shiva/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:8: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere

0

In [77]:
# Iterate through each symbol in the collection, uncomment the code to see the results
#index_price = db.index_price.find()
#index_price = db.index_price_hist.find()
#for ind in index_price:
#    print(ind)
db.index_price_hist.count()

/Users/Shiva/anaconda3/envs/PythonData/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere

500

In [70]:


#list_index=response_json["results"]
index_price = db.index_price.find()
data = pd.DataFrame(list(index_price))
 

    
dict_data = data.to_dict
dict_data

<bound method DataFrame.to_dict of                         _id   close dayCode exchange  fiftyTwoWkHigh  \
0  5da343f1b4883299713008bd  236.21       0     BATS          237.64
1  5da343f1b4883299713008be  247.89       0     BATS          379.49
2  5da343f1b4883299713008bf  272.13       0     BATS          277.98
3  5da343f1b4883299713008c0  172.94       0     BATS          195.72
4  5da343f1b4883299713008c1  116.14       0     BATS          120.40
5  5da51abd84fd000e0dc62d9c  235.87       D   NASDAQ          238.13
6  5da51abd84fd000e0dc62d9d  256.96       D   NASDAQ          379.49
7  5da51abd84fd000e0dc62d9e  271.88       D     AMEX          277.98
8  5da51abd84fd000e0dc62d9f  171.16       D     NYSE          195.72
9  5da51abd84fd000e0dc62da0  116.45       D     NYSE          120.40

  fiftyTwoWkHighDate  fiftyTwoWkLow fiftyTwoWkLowDate flag    high  ...  \
0         2019-10-11         142.00        2019-01-03    s    0.00  ...
1         2018-12-07         176.99        2019-06-03    s    0.00  ...
2         2019-09-19         214.83        2018-12-26    s    0.00  ...
3         2019-05-03         129.77        2018-12-24    s    0.00  ...
4         2019-09-13          91.11        2018-12-26    s    0.00  ...
5         2019-10-14         142.00        2019-01-03    s  238.13  ...
6         2018-12-07         176.99        2019-06-03    s  258.55  ...
7         2019-09-19         214.83        2018-12-26    s  272.45  ...
8         2019-05-03         129.77        2018-12-24    s  173.34  ...
9         2019-09-13          91.11        2018-12-26    s  116.87  ...

                        name  netChange    open percentChange  \
0                  Apple Inc     236.21    0.00          0.00
1                  Tesla Inc     247.89    0.00          0.00
2       S&P 500 ETF Vanguard     272.13    0.00          0.00
3      Alibaba Group Holding     172.94    0.00          0.00
4  JP Morgan Chase & Company     116.14    0.00          0.00
5                  Apple Inc      -0.34  234.90         -0.14
6                  Tesla Inc       9.07  247.90          3.66
7       S&P 500 ETF Vanguard      -0.25  271.79         -0.09
8      Alibaba Group Holding      -1.78  172.84         -1.03
9  JP Morgan Chase & Company       0.31  115.85          0.27

             serverTimestamp  symbol  tick             tradeTimestamp  \
0  2019-10-13T02:35:08-05:00    AAPL        2019-10-10T00:00:00-05:00
1  2019-10-13T03:15:58-05:00    TSLA        2019-10-10T00:00:00-05:00
2  2019-10-13T09:45:02-05:00     VOO        2019-10-10T00:00:00-05:00
3  2019-10-13T08:46:04-05:00    BABA        2019-10-10T00:00:00-05:00
4  2019-10-13T04:18:42-05:00     JPM        2019-10-10T00:00:00-05:00
5  2019-10-14T00:00:00-05:00    AAPL        2019-10-14T00:00:00-05:00
6  2019-10-14T00:00:00-05:00    TSLA        2019-10-14T00:00:00-05:00
7  2019-10-14T00:00:00-05:00     VOO        2019-10-14T00:00:00-05:00
8  2019-10-14T00:00:00-05:00    BABA        2019-10-14T00:00:00-05:00
9  2019-10-14T00:00:00-05:00     JPM        2019-10-14T00:00:00-05:00

  unitCode    volume
0        2         0
1        2         0
2        2         0
3        2         0
4        2         0
5        2  24392500
6        2  10223300
7        2   1216400
8        2   7854100
9        2   8872000

[10 rows x 23 columns]>